# Generated by Django 3.0.7 on 2020-07-24 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=16)),
                ('summary', models.CharField(max_length=128)),
            ],
        ),
        migrations.AlterField(
            model_name='video',
            name='status',
            field=models.IntegerField(choices=[(1, '下线'), (2, '上线')], default=1, verbose_name='状态'),
        ),
    ]
