# Generated by Django 3.0.8 on 2020-08-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_auto_20200807_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(default='shit@qq.com', max_length=254, unique=True, verbose_name='邮箱'),
            preserve_default=False,
        ),
    ]
