# Generated by Django 3.0.7 on 2020-06-28 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='ut',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app01.UserType'),
        ),
    ]
