# Generated by Django 3.0.7 on 2020-07-20 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInof',
            new_name='UserInfo',
        ),
    ]
