# Generated by Django 3.0.7 on 2020-07-20 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20200720_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='username',
            field=models.CharField(db_column='user', db_index=True, max_length=32, null=True, unique=True, verbose_name='用户名'),
        ),
    ]
