# Generated by Django 3.0.7 on 2020-07-20 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20200720_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='user_type',
            field=models.IntegerField(choices=[(0, '普通用户'), (1, '超级用户'), (2, 'VIP')], default=1),
            preserve_default=False,
        ),
    ]
